runtime: php55
api_version: '1'
env: standard
threadsafe: false
instance_class: F1
handlers:
  - url: '/css/*/(.*)'
    application_readable: false
    static_files: "css/\\1"
    require_matching_file: false
    upload: 'css/.*'
  - url: '/img/*/(.*)'
    application_readable: false
    static_files: "img/\\1"
    require_matching_file: false
    upload: 'img/.*'
  - url: '/js/*/(.*)'
    application_readable: false
    static_files: "js/\\1"
    require_matching_file: false
    upload: 'js/.*'
  - url: '/lib/*/(.*)'
    application_readable: false
    static_files: "lib/\\1"
    require_matching_file: false
    upload: 'lib/.*'
  - url: /
    script: index.html
  - url: /(.+)
    script: index.html
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
